#!/bin/bash
# Remove XML files from previous runs
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
rm *xml
#Take the sn from - select unique_identifier from study where study_id = 1;
sn="VIBRANT V240CLD"
mf="$sn"".map.xml"
xf="$sn"".xml"
java -jar export.jar -h prod2 -p 5432 -sname "$sn" -U clinica -P clinica -D v240 -mapFile "$mf" -xmlFile "$xf"
sed -i s/mmddyy10/IS8601DA/ *.xml
zf="$sn".z
export PGPASSWORD=9701485dl
psql -Upostgres -hprod2 v240 < /code/cc-portal/webapp/schema/epro/csv_extract_for_stats.sql
echo "Now zipping the csv files"
zip   "$zf"  /tmp/*.csv
echo "Now zipping the xml files"
zip   "$zf"  *xml
#bcc="dl@software.co.il"
to="frederic.deutsch@gmail.com"
#to="rivkygrin@gmail.com"
bcc="rivkar@clearclinica.com,dl@software.co.il"
#
echo "Greetings from the daily data export for $sn.  Download and unzip the attached file to extract the  files" | mutt -s "$sn data export" "$to"  -a "$zf" -b "$bcc" -e 'my_hdr From:ClearClinica<no-reply@repnets.com>'
rm *.xml
rm /tmp/*.csv
exit 0
