#!/bin/bash
sn=$1
reportpath="/reports/sasexport/"
cd "$reportpath" 
mf="$sn"".map.xml"
xf="$sn"".xml"
echo "Now zipping the files"
today=`date '+%Y_%m_%d'`;
zf="$sn""_""$today".z
zip "$zf" "$mf"
zip "$zf" "$xf"
exit 0
